### PR TITLE
HHS Hospital Data (state level)

### PR DESCRIPTION
**Pull request by cc7768**
Happy Thanksgiving @mikelehen -- This scraper should be able to download the state-level hospital data we've talked about.

FYI: @sglyon @ghop02 @TomGoBravo

### CODE REVIEW

**Comment by cc7768** [comment]
Oops -- I think I scraped the wrong data set :facepalm:

I'll add the other data set to this PR as well :sweat_smile:

**Comment by cc7768** [comment]
This PR has been updated to get the [HHS state data set](https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-state-timeseries). It's passing, but let's wait for (1) @sglyon to review and (2) @mikelehen to green light that we're ready to use the data from this data set.

**Comment by mikelehen** [comment]
Sweet! Yeah, let's not merge just yet. We can sync at data quality review tomorrow.

**Comment by cc7768** [comment]
Closing in favor of #20

**Pull request closed without merging**
