### PR TITLE
WIP idaho  county vaccines

### PR DESCRIPTION
**Pull request by sglyon**
*NOT READY FOR REVIEW*

Posting here to get some comments/suggestions/feedback.

I'm a bit stuck on this one... we can see the first dose and second dose data by county by clicking the filter button on the dashboard. I noticed that when the button is clicked, another request is sent to the tableau server. I tried to follow it, but didn't see where the actual data comes through.

cc @christopherturner @MattSidor

### CODE REVIEW

**Comment by cc7768** [comment]
Also cc @ChrisBremer

**Comment by ChrisBremer** [comment]
The URL filter expression is embedded in the radiobutton command:   `[federated.1unllaw1cp9kx41ckjo6d1cjr4ub].[none:SERIES%20COMPLETE:nk]=y`

So the full link to the [second-dose data](https://public.tableau.com/views/COVID-19VaccineDataDashboard/Residence?%3Aembed=y&%3AshowVizHome=no&%3Adisplay_count=y&%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Alanguage=en&:embed=y&:showVizHome=n&:apiID=host0&[federated.1unllaw1cp9kx41ckjo6d1cjr4ub].[none:SERIES%20COMPLETE:nk]=y) and the [first dose data](https://public.tableau.com/views/COVID-19VaccineDataDashboard/Residence?%3Aembed=y&%3AshowVizHome=no&%3Adisplay_count=y&%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Alanguage=en&:embed=y&:showVizHome=n&:apiID=host0&[federated.1unllaw1cp9kx41ckjo6d1cjr4ub].[none:SERIES%20COMPLETE:nk]=n) just get it appended with a y/n boolean.

**Comment by christopherturner** [comment]
Just found that filter function as well!  Using the `TableauDashboard` class, this may be a more efficient starting point for the class on the attached commit:

```
class IdahoVaccineCounty(TableauDashboard):
    state_fips = int(us.states.lookup("Idaho").fips)
    source = "https://coronavirus.idaho.gov/covid-19-vaccine/"
    baseurl = "https://public.tableau.com"

    provider = "state"
    has_location = False

    def fetch(self):
        self.filterFunctionName = "[federated.1unllaw1cp9kx41ckjo6d1cjr4ub].[none:SERIES COMPLETE:nk]"
        self.filterFunctionValue = "y" # You'll need to do "get_tableau_view()" each possible filter value
        self.viewPath = "COVID-19VaccineDataDashboard/Residence"
        return self.get_tableau_view()
```

I did something similar with iterating through filter values in ca_testing.py.

**Comment by sglyon** [comment]
Thanks team!

I tried something like that in these lines: https://github.com/covid-projections/can-scrapers/pull/114/files#diff-1ae497dd0444dc238413312d4e82eaf11dad991215304951bb09d940f436b9f4R27-R30

Have you attempted to run that code to see if it gets the data we need?

**Pull request closed without merging**
