### PR TITLE
BuxFix for WY Vaccine Scraper

### PR DESCRIPTION
**Pull request by blew2015**
Patched up the WY Vaccine Scraper

### CODE REVIEW

**Comment by blew2015** [comment]
@sglyon It is not letting me request a review from you for some reason, but this should be done.

**Comment by blew2015** [comment]
@cc7768 It was not letting me request a review, so I am mentioning you in this thread in lieu of formally requesting a review.

**Comment by sglyon** [comment]
Awesome, thank you @blew2015 

Would you be willing to write up a quick note about how you found these magic jsons?

That would help with maintenance going forward. Thanks!

**Comment by sglyon** [comment]
I'm going to merge to get the fix in, but that note would be very helpful

Thanks for making time for the fix @blew2015 !

**Comment by blew2015** [comment]
No worries. I will draft up a quick email and put you and Chase on it before EOD today. Is there anyone else I should include on it?

**Comment by sglyon** [comment]
Nope, that's great. We will make sure to include it somewhere the team can see it!

**Pull request merged**
