### PR TITLE
ENH: added schema entries for vaccine data

### PR DESCRIPTION
**Pull request by sglyon**
Closes Vaccine Schema #73

### CODE REVIEW

**Review by mikelehen — APPROVED** [review]
👍

**Comment by smcclure17** [comment]
_Not sure if this is the right/relevant place for this, so if there's a better place to put this I can move it._ 

Here are the data categories/variables that CDC data return. 

### Pfizer:

- [Dataset info](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/saz5-9hgg)
- [Data source](https://data.cdc.gov/resource/saz5-9hgg.json)

**Description:** 
> This dataset lists the allocations of doses made available for states and jurisdictions to order against. Weekly allocations are provided to states on Tuesdays; after doses are ordered by states, shipments begin the following Monday.

| variables/columns                                       |
| -------------------------------------------------- |
| jurisdiction _(state)_                                       |
| hhs\_region                                        |
| first\_doses\_12\_14                               |
| second\_doses\_shipment\_12\_14                    |
| doses\_allocated\_week\_of\_12\_21                 |
| second\_dose\_shipment\_12\_17                     |
| doses\_allocated\_week\_of\_12\_28                 |
| second\_dose\_shipment\_12\_28                     |
| doses\_allocated\_week\_of\_01\_04                 |
| second\_dose\_shipment\_01\_04                     |
| total\_pfizer\_allocation\_first\_dose\_shipments  |
| total\_allocation\_pfizer\_second\_dose\_shipments |

----------------------------------

### Moderna

- [Dataset info](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/b7pe-5nws)
- [Data source](https://data.cdc.gov/resource/b7pe-5nws.json)

**Description:** 
_same as pfizer_

|variables/columns                                        |
| --------------------------------------------------- |
| jurisdiction _(state)_                                         |
| hhs\_region                                         |
| doses\_allocated\_week\_12\_21                      |
| second\_dose\_shipment\_12\_21                      |
| doses\_allocated\_week\_12\_28                      |
| second\_dose\_shipment\_12\_28                      |
| doses\_allocated\_week\_01\_04                      |
| second\_dose\_shipment\_01\_04                      |
| doses\_allocated\_week\_of\_01\_10                  |
| second\_dose\_shipment\_week\_of\_01\_10            |
| total\_moderna\_allocation\_first\_dose\_shipments  |
| total\_allocation\_moderna\_second\_dose\_shipments |

----------------------------------

### Total/Snapshot

- [Dataset Info](https://covid.cdc.gov/covid-data-tracker/#vaccinations)
- [Data source](https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data)


**Description:**
> Doses distributed and people initiating vaccination (1st dose received) are for both Moderna and Pfizer BioNTech COVID-19 vaccine and reflect current data available as of 9:00am ET on the day of reporting. Data will be regularly updated daily, Monday through Friday. Updates will occur the following day when reporting coincides with a federal holiday.

> Doses distributed are cumulative counts of COVID-19 vaccine doses recorded as shipped in the Centers for Disease Control and Prevention’s (CDC) Vaccine Tracking System (VTrckS) since December 13, 2020.

> People initiating vaccination (1st dose received) are cumulative counts of individual COVID-19 vaccine first **doses administered** as reported to the CDC by state, territorial, and local public health agencies and four federal entities...

| variables/columns               |
| ------------------- |
| Date          |
| MMWR\_week          |
| Location _(state abbreviation)_            |
| ShortName           |
| LongName _(state name)_           |
| Doses\_Distributed  |
| Doses\_Administered |
| Dist\_Per\_100K     |
| Admin\_Per\_100K    |

----------------------------------
_As I work more I can update this comment with more information_

**Review by cc7768 — APPROVED** [review]
This looks good to me too.

**Comment by smcclure17** [comment]
_from a call with @sglyon and @MattSidor_. I think this is what we discussed, but if I'm incorrect or missing anything please correct me. 

Adding the ability to track first/second doses in allocation (and potentially distribution.)

In `covid_catagories.csv` add
`vaccine,moderna_vaccine_first_dose_allocated`
`vaccine,moderna_vaccine_second_dose_allocated`
`vaccine,pfizer_vaccine_first_dose_allocated`
`vaccine,pfizer_vaccine_second_dose_allocated`

In `covid_variables.csv` add
`moderna_vaccine_first_dose_allocated,cumulative,doses`
`moderna_vaccine_second_dose_allocated,cumulative,doses`
`pfizer_vaccine_first_dose_allocated,cumulative,doses`
`pfizer_vaccine_second_dose_allocated,cumulative,doses`

This could be expanded to include first and second doses for  `_vaccine_distributed` as well, depending on the data we find.

**Comment by mikelehen** [comment]
I'm surprised first_dose / second_dose are showing up in the "allocated" category.  Out of curiosity, is there actually a physical distinction between "first dose" and "second dose" when it comes to allocation (and distribution)?  Are the actual vaccine vials different?  Or is this purely an accounting distinction?

**Comment by smcclure17** [comment]
I think it's just an accounting distinction. [This page](https://www.cdc.gov/vaccines/covid-19/info-by-product/moderna/index.html) (under scheduling doses) says that  _"Both doses should be Pfizer-BioNTech COVID-19 vaccine_" and "_Both doses of the series should be completed with the same product_"  (the same is said on the Moderna page). But, I haven't seen anything to explicitly indicate the doses are the same.

The distinction of first/second dose allocation comes from the `Total Pfizer Allocation "First Dose" Shipments` and `Total Allocation Pfizer "Second Dose" Shipments` columns from [here.](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/saz5-9hgg)

The datasets are a bit confusing, but I believe these are allocated counts (not shipped/distributed) b/c the numbers are larger than the distributed numbers from [this dashboard](https://covid.cdc.gov/covid-data-tracker/#vaccinations)

**Pull request merged**
